import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { FC } from "react";

interface ParameterViewerProps {
  title: string;
  subtitle: string;
  paramsJson: string | null;
}

const ParameterViewer: FC<ParameterViewerProps> = ({
  title,
  subtitle,
  paramsJson,
}) => {
  const params = paramsJson ? JSON.parse(paramsJson) : undefined;

  return (
    <Card>
      <CardHeader className="rounded-lg rounded-b-none border-b py-4 bg-gray-50 dark:bg-background">
        <CardTitle className="text-base">{title}</CardTitle>
        <CardDescription className="text-sm text-muted-foreground">
          {subtitle}
        </CardDescription>
      </CardHeader>
      <CardContent className="py-4">
        <div className="flex flex-col gap-2">
          {(!params || Object.keys(params).length === 0) && (
            <p className="text-sm">No parameters generated by this phase</p>
          )}
          {params &&
            Object.entries(params).map(([key, value]) => (
              <div key={key} className="flex justify-between items-center space-y-1">
                <p className="text-sm text-muted-foreground flex-1 basis-1/3">{key}</p>
                <Input readOnly className="flex-1 basis-2/3" value={value as string}/>
              </div>
            ))}
        </div>
      </CardContent>
    </Card>
  );
};

export default ParameterViewer;
